apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: dXNlcg==
  MYSQL_DATABASE: YmlrZVJlbnRTeXN0ZW0=