version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bikeRentSystem
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - bike-network

  bike-app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: bikeRentSystem
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bike-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bike-app
    networks:
      - bike-network
      
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    networks:
      - bike-network
      
volumes:
  mysql-data:

networks:
  bike-network:
    driver: bridge