apiVersion: v2
name: bikes-chart
description: A Helm chart for bikes rent application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: "bike-app"
    version: "0.1.0"
    repository: "file://./charts/bike-app"
  - name: "db"
    version: "0.1.0"
    repository: "file://./charts/db"
